-- Seed data: lugares de ejemplo para Andahuaylas Go
-- Ejecutar DESPUÉS de supabase-migrate.sql en el SQL Editor de Supabase

INSERT INTO lugares (nombre, tipo, categoria, subcategoria, descripcion, direccion, distrito, latitud, longitud, horario, telefono, activo, rating, reviews_count, imagen_url, galeria, rango_precio, etiquetas, creado_en)
VALUES
(
  'Complejo Arqueológico de Sóndor',
  'turismo',
  'Arqueología',
  'Arqueología',
  'Sóndor es un complejo arqueológico monumental ubicado en el distrito de Pacucha, provincia de Andahuaylas. Considerado un centro ceremonial y militar estratégico de la cultura Chanka.',
  'Distrito de Pacucha, Provincia de Andahuaylas',
  'Pacucha',
  -13.6012, -73.3155,
  '{"lunes_domingo": "8:00 AM - 5:00 PM"}',
  '+51 987 654 321',
  true, 4.8, 124,
  'https://picsum.photos/seed/sondor/800/600',
  '["https://picsum.photos/seed/sondor1/800/600","https://picsum.photos/seed/sondor2/800/600","https://picsum.photos/seed/sondor3/800/600"]',
  'General: S/. 5.00, Estudiantes: S/. 2.00',
  '["Aventura","Cultura","Historia"]',
  NOW()
),
(
  'Laguna de Pacucha',
  'turismo',
  'Naturaleza',
  'Naturaleza',
  'La laguna de Pacucha es uno de los espejos de agua más bellos de la región Apurímac. Ideal para paseos en bote, pesca deportiva y observación de aves. Sus aguas turquesas contrastan con el verde intenso de los Andes.',
  'Distrito de Pacucha',
  'Pacucha',
  -13.6075, -73.3300,
  '{"lunes_domingo": "6:00 AM - 6:00 PM"}',
  '+51 983 456 789',
  true, 4.6, 89,
  'https://picsum.photos/seed/pacucha/800/600',
  '["https://picsum.photos/seed/pacucha1/800/600","https://picsum.photos/seed/pacucha2/800/600"]',
  'Libre',
  '["Naturaleza","Paisaje","Turismo"]',
  NOW()
),
(
  'Restaurante Sol de los Chankas',
  'gastronomia',
  'Comida Tradicional',
  'Comida Tradicional',
  'Disfruta de la auténtica comida chanka con vista al valle. Especialidad en cuy al horno, pachamanca y trucha frita. Ambiente familiar y acogedor con ingredientes frescos de la zona.',
  'Jr. Juan Francisco Ramos 456, Andahuaylas',
  'Andahuaylas',
  -13.6380, -73.3850,
  '{"lunes_sabado": "10:00 AM - 10:00 PM", "domingo": "10:00 AM - 6:00 PM"}',
  '+51 986 123 456',
  true, 4.5, 67,
  'https://picsum.photos/seed/restaurante_chankas/800/600',
  '["https://picsum.photos/seed/rest_chankas1/800/600","https://picsum.photos/seed/rest_chankas2/800/600"]',
  'S/. 15 - S/. 45',
  '["Tradicional","Familiar","Cuy","Pachamanca"]',
  NOW()
),
(
  'Mercado Artesanal de Talavera',
  'comercio',
  'Artesanías',
  'Artesanías',
  'El mercado artesanal más grande de la provincia. Encuentra textiles tejidos a mano, cerámica tradicional, joyería en plata y recuerdos típicos de la cultura Chanka. Ideal para llevar un pedazo de Andahuaylas a casa.',
  'Av. Principal s/n, Talavera',
  'Talavera',
  -13.6520, -73.4150,
  '{"lunes_domingo": "8:00 AM - 8:00 PM"}',
  '+51 984 567 890',
  true, 4.3, 45,
  'https://picsum.photos/seed/talavera/800/600',
  '["https://picsum.photos/seed/talavera1/800/600","https://picsum.photos/seed/talavera2/800/600","https://picsum.photos/seed/talavera3/800/600"]',
  'Varía según producto',
  '["Artesanía","Textiles","Recuerdos","Cultura"]',
  NOW()
),
(
  'Hotel Valle Sagrado',
  'hospedaje',
  'Hotel',
  'Hotel',
  'Hotel boutique con vista panorámica al valle de Andahuaylas. Habitaciones cómodas con calefacción, agua caliente las 24 horas, restaurante interno y tour organizado a los principales atractivos turísticos de la zona.',
  'Cerro San Cristóbal 789, Andahuaylas',
  'Andahuaylas',
  -13.6320, -73.3770,
  '{"lunes_domingo": "Check-in: 1:00 PM, Check-out: 11:00 AM"}',
  '+51 981 234 567',
  true, 4.2, 34,
  'https://picsum.photos/seed/hotel_valle/800/600',
  '["https://picsum.photos/seed/hotel_valle1/800/600","https://picsum.photos/seed/hotel_valle2/800/600"]',
  'S/. 80 - S/. 180',
  '["Hotel","Cómodo","Vista","Descanso"]',
  NOW()
);
